### ISSUE TITLE
Compiling for ARM

### ISSUE THREAD

**Issue by pabloaledo** [samtools/htscodecs#98]
Hello, we are trying to compile htscodecs in an arm64 machine, and in that architecture the value of `HWCAP_ASIMD` in https://github.com/samtools/htscodecs/blob/5aecc6e107db1c2ff59529a5aa034d28b799b7d1/htscodecs/rANS_static4x16pr.c#L1021 is not defined. Could you help us to identify what's the purpose of this value and if possible, see how to assign a value for that constant?. It would be very useful to be able to compile hts for ARM, and this seems to be the only blocking thing.

**Comment by jkbonfield** [comment]
Does https://github.com/samtools/htscodecs/pull/91 cure this for you?

**Comment by jkbonfield** [comment]
Closing as we believe the issue to be resolved already.
